# Generated by Django 5.0.1 on 2024-05-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Defaulter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=350)),
                ('national_id', models.CharField(max_length=50)),
                ('customer_location', models.CharField(max_length=50)),
                ('bussiness_type', models.CharField(help_text='type of business cutomer runs', max_length=50)),
                ('number_of_loans_taken', models.IntegerField(default=1)),
                ('amount_in_default', models.IntegerField(default=0)),
                ('date_defaulted', models.DateField()),
                ('company_defaulted', models.CharField(max_length=50)),
                ('cleared', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
