# Generated by Django 5.0.1 on 2024-06-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='username',
        ),
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.EmailField(default='pravison@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
